import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { db } from "@/lib/db";
import { getDemoEmployer } from "@/lib/demo-user";
import { compensationRange } from "@/lib/compensation";
import { jobFromDb } from "@/lib/db-mappers";

export const dynamic = "force-dynamic";
const PAGE_SIZE = 25;

export default async function EmployerJobsPage({ searchParams }: { searchParams: Promise<{ q?: string; contract?: string; mode?: string; status?: string; page?: string }> }) {
  const employer = await getDemoEmployer(); const params = await searchParams; const page = Math.max(1, Number(params.page) || 1); const query = params.q?.trim() ?? "";
  const where = { ownerId: employer.id, ...(query ? { OR: [{ rawTitle: { contains: query, mode: "insensitive" as const } }, { displayTitle: { contains: query, mode: "insensitive" as const } }, { company: { contains: query, mode: "insensitive" as const } }, { occupation: { contains: query, mode: "insensitive" as const } }] } : {}), ...(params.contract ? { contractType: params.contract } : {}), ...(params.mode ? { workMode: params.mode } : {}), ...(params.status === "published" ? { published: true } : params.status === "draft" ? { published: false } : {}) };
  const [jobs, total] = await Promise.all([db.job.findMany({ where, include: { _count: { select: { applications: true, matches: true } }, matches: { orderBy: { score: "desc" }, take: 20, select: { score: true, breakdown: true } } }, orderBy: { updatedAt: "desc" }, skip: (page - 1) * PAGE_SIZE, take: PAGE_SIZE }), db.job.count({ where })]);
  const pages = Math.max(1, Math.ceil(total / PAGE_SIZE));
  const href = (nextPage: number) => `/employer/jobs?${new URLSearchParams({ ...(query ? { q: query } : {}), ...(params.contract ? { contract: params.contract } : {}), ...(params.mode ? { mode: params.mode } : {}), ...(params.status ? { status: params.status } : {}), page: String(nextPage) })}`;
  return <AppShell role="employer"><div className="page-head"><div><h1>Tin tuyển dụng của tôi</h1><p>{total} tin · trang {page}/{pages}. Xem ứng viên phù hợp cho từng nhu cầu tuyển dụng.</p></div><Link className="btn btn-primary" href="/employer/jobs/new" prefetch={false}>＋ Tạo tin mới</Link></div>
    <form className="card filter-bar" style={{ marginBottom: 18 }}><input className="input" name="q" defaultValue={query} placeholder="Tìm chức danh, công ty, nghề..."/><select className="input" name="contract" defaultValue={params.contract ?? ""}><option value="">Mọi hợp đồng</option><option value="full_time">Full-time</option><option value="part_time">Part-time</option><option value="freelance">Freelance</option><option value="project_based">Theo dự án</option><option value="internship">Thực tập</option></select><select className="input" name="mode" defaultValue={params.mode ?? ""}><option value="">Mọi hình thức</option><option value="remote">Remote</option><option value="hybrid">Hybrid</option><option value="onsite">Onsite</option></select><select className="input" name="status" defaultValue={params.status ?? ""}><option value="">Mọi trạng thái</option><option value="published">Đang tuyển</option><option value="draft">Bản nháp</option></select><button className="btn btn-primary" type="submit">Lọc</button></form>
    <div className="card">{jobs.length ? jobs.map((record) => { const job = jobFromDb(record); const green = record.matches.filter((match) => (match.breakdown as Record<string, unknown>).fitStatus === "qualified").length; const yellow = record.matches.filter((match) => (match.breakdown as Record<string, unknown>).fitStatus === "skill_gap").length; const red = record.matches.length - green - yellow; return <div className="job-manage-row" key={record.id}><div><h3><Link href={`/employer/jobs/${record.id}`} prefetch={false}>{record.displayTitle ?? record.rawTitle}</Link></h3><p>{record.company} · {record.contractType ?? "Chưa rõ"} · {record.workMode ?? "Chưa rõ"} · {compensationRange(job.compensation)}</p><small>{record.published ? "Đang tuyển" : "Bản nháp"} · {record._count.applications} đơn · {record._count.matches} ứng viên matching{record.matches[0] ? ` · cao nhất ${record.matches[0].score}%` : ""}</small><div className="tags" style={{ marginTop: 8 }}><span className="badge green">{green} phù hợp</span><span className="badge amber">{yellow} còn thiếu</span><span className="badge red">{red} không hợp</span></div></div><div className="tags"><Link className="btn btn-light btn-sm" href={`/employer/jobs/${record.id}`} prefetch={false}>Chi tiết</Link><Link className="btn btn-primary btn-sm" href={`/employer/jobs/${record.id}/matches`} prefetch={false}>Xem ứng viên</Link></div></div>; }) : <div className="empty">Không tìm thấy tin phù hợp bộ lọc.</div>}</div>
    <div className="pagination" style={{ marginTop: 18, display: "flex", justifyContent: "space-between" }}><Link className={`btn btn-light ${page <= 1 ? "disabled" : ""}`} aria-disabled={page <= 1} href={page <= 1 ? href(1) : href(page - 1)} prefetch={false}>← Trang trước</Link><span className="badge blue">{page}/{pages}</span><Link className={`btn btn-light ${page >= pages ? "disabled" : ""}`} aria-disabled={page >= pages} href={page >= pages ? href(pages) : href(page + 1)} prefetch={false}>Trang sau →</Link></div>
  </AppShell>;
}
