export type TaxonomySeed = {
  id: string;
  type: string;
  name: string;
  aliases: string[];
  parentId?: string;
};

export const taxonomyCatalog: TaxonomySeed[] = [
  { id: "technology", type: "root", name: "Technology", aliases: ["công nghệ", "technology"] },
  { id: "creative", type: "root", name: "Creative", aliases: ["sáng tạo", "creative industry"] },
  { id: "information_technology", type: "field", name: "Information Technology", aliases: ["công nghệ thông tin", "cntt", "it"], parentId: "technology" },
  { id: "cybersecurity", type: "specialization", name: "Cybersecurity", aliases: ["an toàn thông tin", "bảo mật", "security"], parentId: "information_technology" },
  { id: "data_ai", type: "specialization", name: "Data and AI", aliases: ["dữ liệu và ai", "data ai"], parentId: "information_technology" },
  { id: "infrastructure_cloud", type: "specialization", name: "Infrastructure and Cloud", aliases: ["hạ tầng và cloud", "cloud infrastructure"], parentId: "information_technology" },
  { id: "digital_product", type: "specialization", name: "Digital Product", aliases: ["sản phẩm số", "digital product"], parentId: "information_technology" },
  { id: "occupations", type: "field", name: "Occupations", aliases: ["nghề nghiệp", "job roles"] },
  { id: "generic_skills", type: "skill_group", name: "Skills", aliases: ["kỹ năng", "competencies"] },
  { id: "content_media", type: "field", name: "Content and Media", aliases: ["nội dung và truyền thông", "content media"], parentId: "creative" },
  { id: "design_multimedia", type: "specialization", name: "Design and Multimedia", aliases: ["đồ họa đa phương tiện", "multimedia design"], parentId: "creative" },
  { id: "creative_tools", type: "skill_group", name: "Creative Tools", aliases: ["công cụ sáng tạo", "design tools"], parentId: "creative" },
  { id: "software_development", type: "specialization", name: "Software Development", aliases: ["lập trình phần mềm", "software engineering"], parentId: "information_technology" },
  { id: "web_development", type: "specialization", name: "Web Development", aliases: ["lập trình web", "web dev"], parentId: "software_development" },
  { id: "technical_skills", type: "skill_group", name: "Technical Skills", aliases: ["kỹ năng kỹ thuật", "tech skills"], parentId: "technology" },
  { id: "frontend_skills", type: "skill_group", name: "Frontend Skills", aliases: ["kỹ năng frontend"], parentId: "technical_skills" },
  { id: "backend_skills", type: "skill_group", name: "Backend Skills", aliases: ["kỹ năng backend"], parentId: "technical_skills" },
  { id: "data_skills", type: "skill_group", name: "Data Skills", aliases: ["kỹ năng dữ liệu"], parentId: "technical_skills" },
  { id: "business_domains", type: "domain_group", name: "Business Domains", aliases: ["lĩnh vực kinh doanh"] },
  { id: "languages", type: "language_group", name: "Languages", aliases: ["ngôn ngữ"] },
  { id: "certifications", type: "certification_group", name: "Certifications", aliases: ["chứng chỉ", "bằng cấp"] },
  { id: "frontend_web_developer", type: "occupation", name: "Frontend Web Developer", aliases: ["frontend", "front end", "frontend developer", "front-end developer", "fe dev", "fe", "lập trình viên frontend", "dev giao diện"], parentId: "web_development" },
  { id: "backend_developer", type: "occupation", name: "Backend Developer", aliases: ["backend", "back end", "back-end developer", "be dev", "be", "backend dev", "lập trình viên backend"], parentId: "web_development" },
  { id: "fullstack_developer", type: "occupation", name: "Full-stack Developer", aliases: ["full stack", "fullstack", "fs dev", "fs", "lập trình viên fullstack"], parentId: "web_development" },
  { id: "mobile_developer", type: "occupation", name: "Mobile Developer", aliases: ["mobile dev", "app developer", "lập trình ứng dụng"], parentId: "software_development" },
  { id: "devops_engineer", type: "occupation", name: "DevOps Engineer", aliases: ["devops", "cloud engineer", "kỹ sư devops"], parentId: "infrastructure_cloud" },
  { id: "data_analyst", type: "occupation", name: "Data Analyst", aliases: ["da", "data analytics", "chuyên viên phân tích dữ liệu"], parentId: "data_ai" },
  { id: "data_engineer", type: "occupation", name: "Data Engineer", aliases: ["de", "kỹ sư dữ liệu"], parentId: "data_ai" },
  { id: "machine_learning_engineer", type: "occupation", name: "Machine Learning Engineer", aliases: ["ml engineer", "ml eng", "ai engineer", "ai/ml", "kỹ sư ai"], parentId: "data_ai" },
  { id: "qa_engineer", type: "occupation", name: "QA Engineer", aliases: ["qa", "qc", "tester", "software tester", "kiểm thử phần mềm"], parentId: "software_development" },
  { id: "cybersecurity_analyst", type: "occupation", name: "Cybersecurity Analyst", aliases: ["security analyst", "chuyên viên an toàn thông tin", "chuyên viên bảo mật"], parentId: "cybersecurity" },
  { id: "ui_ux_designer", type: "occupation", name: "UI/UX Designer", aliases: ["ui ux", "ux designer", "ui designer", "product designer"], parentId: "digital_product" },
  { id: "content_creator", type: "occupation", name: "Content Creator", aliases: ["content creator", "nhà sáng tạo nội dung", "sáng tạo nội dung"], parentId: "content_media" },
  { id: "javascript", type: "skill", name: "JavaScript", aliases: ["js", "ecmascript"], parentId: "frontend_skills" },
  { id: "typescript", type: "skill", name: "TypeScript", aliases: ["ts"], parentId: "frontend_skills" },
  { id: "react", type: "skill", name: "React", aliases: ["reactjs", "react.js", "react js"], parentId: "javascript" },
  { id: "nextjs", type: "skill", name: "Next.js", aliases: ["nextjs", "next js", "next"], parentId: "react" },
  { id: "vuejs", type: "skill", name: "Vue.js", aliases: ["vue", "vuejs", "vue js"], parentId: "javascript" },
  { id: "angular", type: "skill", name: "Angular", aliases: ["angularjs"], parentId: "javascript" },
  { id: "nodejs", type: "skill", name: "Node.js", aliases: ["node", "nodejs", "node js"], parentId: "backend_skills" },
  { id: "nestjs", type: "skill", name: "NestJS", aliases: ["nest", "nest.js"], parentId: "nodejs" },
  { id: "expressjs", type: "skill", name: "Express.js", aliases: ["express", "expressjs"], parentId: "nodejs" },
  { id: "html", type: "skill", name: "HTML", aliases: ["html5"], parentId: "frontend_skills" },
  { id: "css", type: "skill", name: "CSS", aliases: ["css3"], parentId: "frontend_skills" },
  { id: "tailwind_css", type: "skill", name: "Tailwind CSS", aliases: ["tailwind", "tw css"], parentId: "css" },
  { id: "mongodb", type: "skill", name: "MongoDB", aliases: ["mongo"], parentId: "data_skills" },
  { id: "postgresql", type: "skill", name: "PostgreSQL", aliases: ["postgres", "psql"], parentId: "data_skills" },
  { id: "mysql", type: "skill", name: "MySQL", aliases: ["mysql db"], parentId: "data_skills" },
  { id: "docker", type: "skill", name: "Docker", aliases: ["container docker"], parentId: "technical_skills" },
  { id: "kubernetes", type: "skill", name: "Kubernetes", aliases: ["k8s"], parentId: "docker" },
  { id: "rest_api", type: "skill", name: "REST API", aliases: ["restful api", "rest api"] },
  { id: "graphql", type: "skill", name: "GraphQL", aliases: ["gql"] },
  { id: "git", type: "skill", name: "Git", aliases: ["github", "gitlab"] },
  { id: "python", type: "skill", name: "Python", aliases: ["py"] },
  { id: "java", type: "skill", name: "Java", aliases: ["java core"] },
  { id: "dotnet", type: "skill", name: ".NET", aliases: ["dotnet", ".net", "c#", "csharp"] },
  { id: "react_native", type: "skill", name: "React Native", aliases: ["rn"], parentId: "react" },
  { id: "flutter", type: "skill", name: "Flutter", aliases: ["dart flutter"] },
  { id: "veo3", type: "skill", name: "Veo 3", aliases: ["veo3", "google veo 3", "veo"] , parentId: "creative_tools" },
  { id: "adobe_creative_cloud", type: "skill", name: "Adobe Creative Cloud", aliases: ["adobe", "adebe", "photoshop", "illustrator", "after effects", "premiere pro"], parentId: "creative_tools" },
  { id: "ecommerce", type: "domain", name: "E-commerce", aliases: ["ecommerce", "e commerce", "thương mại điện tử", "tmđt"], parentId: "business_domains" },
  { id: "fintech", type: "domain", name: "Fintech", aliases: ["financial technology", "công nghệ tài chính"] },
  { id: "fashion", type: "domain", name: "Fashion", aliases: ["thời trang"] },
  { id: "saas", type: "domain", name: "SaaS", aliases: ["software as a service"] },
  { id: "remote", type: "work_mode", name: "Remote", aliases: ["work from home", "wfh", "từ xa"] },
  { id: "hybrid", type: "work_mode", name: "Hybrid", aliases: ["kết hợp"] },
  { id: "onsite", type: "work_mode", name: "On-site", aliases: ["onsite", "tại văn phòng"] },
  { id: "english", type: "language", name: "English", aliases: ["english", "tiếng anh", "tieng anh", "ta", "anh văn"], parentId: "languages" },
  { id: "english_certificate", type: "certification", name: "English-language certificate", aliases: ["bằng tiếng anh", "bang tieng anh", "bằng ta", "chứng chỉ tiếng anh", "english certificate"], parentId: "certifications" },
];
